create table employee
(
	id integer generated by default as identity
		constraint employee_pkey
			primary key,
	created_at timestamp,
	created_by integer,
	updated_by integer,
	updated_on timestamp,
	email varchar(255) not null
		constraint employee_unique_email_constraint
			unique,
	password varchar(66) not null
);

create table department
(
	id integer generated by default as identity
		constraint departments_pkey
			primary key,
	created_at timestamp,
	created_by integer,
	updated_by integer,
	updated_on timestamp,
	name varchar(255) not null
		constraint department_unique_name_constraint
			unique,
	employee_id integer
		constraint department_employee_id_fk
			references employee,
	manager_id integer
		constraint department_manager_id_fk
			references employee
);

create table "hr_user"
(
	id integer generated by default as identity
		constraint user_pkey
			primary key,
	created_at timestamp,
	created_by integer,
	updated_by integer,
	updated_on timestamp,
	address varchar(255),
	birth_date timestamp,
	email varchar(255) not null
		constraint hr_user_unique_email_constraint
			unique,
	first_name varchar(255),
	last_name varchar(255),
	password varchar(128) not null,
	phone varchar(255),
	valid_until timestamp,
	profile_picture bytea
);

